# Generated by Django 3.2.6 on 2021-11-28 19:23

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211128_1921'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('follower', django.db.models.expressions.F('followed')), _negated=True), name='users_follow_prevent_self_follow'),
        ),
    ]
