# Generated by Django 3.2 on 2021-08-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="Bio"),
        ),
        migrations.AddField(
            model_name="user",
            name="cover",
            field=models.ImageField(
                blank=True, upload_to="img/profile/covers", verbose_name="Cover Photo"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Link"),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Location"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True,
                upload_to="img/profile/photos",
                verbose_name="User personal photo",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(max_length=200, verbose_name="full name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="short_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="short name"
            ),
        ),
    ]
