# Generated by Django 3.2.6 on 2021-11-28 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_follow_users_follow_prevent_self_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_followers',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='users_follow_prevent_self_follow',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='followed',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='target',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='users.Follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('source', 'target'), name='users_follow_unique_followers'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('source', django.db.models.expressions.F('target')), _negated=True), name='users_follow_prevent_self_follow'),
        ),
    ]
