version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - tweety
    env_file: .env.dev
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - tweety
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    links:
      - db
    depends_on:
      - db
    env_file: .env.dev

  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    command: /code/docker/django/start
    env_file: .env.dev
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - tweety

networks:
  tweety:
    driver: bridge

volumes:
  postgres:
  pgadmin:
