# Generated by Django 3.2.6 on 2021-12-03 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=280, verbose_name='Full Text')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('in_reply_to_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.tweet', verbose_name='In reply to status')),
                ('in_reply_to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='In reply to user')),
            ],
        ),
    ]
