# Generated by Django 3.2.6 on 2021-12-09 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_remove_tweet_in_reply_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='in_reply_to_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.tweet', verbose_name='In reply to status'),
        ),
    ]
