name: ci

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on: [pull_request]

jobs:
  nox:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/python_django

    steps:
      - uses: actions/checkout@v2
      - name: Build the Stack
        run: docker-compose build

      - name: Run nox
        run: docker-compose run django nox

      - name: Tear down the Stack
        run: docker-compose down
      - name: Block Merge Commits
        uses: z3by/block-merge-commits-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
